

export const datas = [
  {
    id: "1",
    name: "name 1",
    gender: "gender 1",
    age: 9,
    city: "city 1",
    image: "http://lorempixel.com/640/480/cats",
  },
  {
    id: "2",
    name: "name 2",
    gender: "gender 2",
    age: 68,
    city: "city 2",
    image: "http://lorempixel.com/640/480/cats",
  },
  {
    id: "3",
    name: "name 3",
    gender: "gender 3",
    age: 49,
    city: "city 3",
    image: "http://lorempixel.com/640/480/animals",
  },
  {
    id: "4",
    name: "name 4",
    gender: "gender 4",
    age: 27,
    city: "city 4",
    image: "http://lorempixel.com/640/480/technics",
  },
  {
    id: "5",
    name: "name 5",
    gender: "gender 5",
    age: 73,
    city: "city 5",
    image: "http://lorempixel.com/640/480/abstract",
  },
  {
    id: "6",
    name: "name 6",
    gender: "gender 6",
    age: 29,
    city: "city 6",
    image: "http://lorempixel.com/640/480/city",
  },
  {
    id: "7",
    name: "name 7",
    gender: "gender 7",
    age: 90,
    city: "city 7",
    image: "http://lorempixel.com/640/480/fashion",
  },
  {
    id: "8",
    name: "name 8",
    gender: "gender 8",
    age: 78,
    city: "city 8",
    image: "http://lorempixel.com/640/480/fashion",
  },
  {
    id: "9",
    name: "name 9",
    gender: "gender 9",
    age: 96,
    city: "city 9",
    image: "http://lorempixel.com/640/480/business",
  },
  {
    id: "10",
    name: "name 10",
    gender: "gender 10",
    age: 6,
    city: "city 10",
    image: "http://lorempixel.com/640/480/fashion",
  },
  {
    id: "11",
    name: "name 11",
    gender: "gender 11",
    age: 60,
    city: "city 11",
    image: "http://lorempixel.com/640/480/technics",
  },
];
